
version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  web:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    command: mix phx.server
    links:
      - postgres
    environment: 
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_URL=ecto://postgres:postgres@postgres/banking_api_dev